all:
  vars:
    ansible_connection: ssh
    ansible_user: ec2-user
    ansible_become: true
    ansible_ssh_private_key_file: '~/.ssh/bargovic-aws-kp.pem'

zookeeper:
  hosts:
    ec2-18-234-219-74.compute-1.amazonaws.com:
      zookeeper_id: 1
    ec2-54-221-67-138.compute-1.amazonaws.com:
      zookeeper_id: 2
    ec2-204-236-203-81.compute-1.amazonaws.com: 
      zookeeper_id: 3

kafka_broker:
  hosts:
    ec2-34-201-120-204.compute-1.amazonaws.com:
      broker_id: 1
    ec2-54-167-102-64.compute-1.amazonaws.com:
      broker_id: 2
    ec2-52-23-197-151.compute-1.amazonaws.com:
      broker_id: 3

schema_registry:
  hosts:
    ec2-54-90-134-30.compute-1.amazonaws.com:
 
kafka_connect:
  hosts:
    ec2-54-159-26-32.compute-1.amazonaws.com:

kafka_rest:
  hosts:
    ec2-50-17-58-3.compute-1.amazonaws.com:

ksql:
  hosts:
    ec2-35-175-176-161.compute-1.amazonaws.com:

control_center:
  hosts:
    ec2-3-91-84-22.compute-1.amazonaws.com:

